language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - pip install python-coveralls mock
  - sudo apt-get install -y rpm
script:
  - nosetests --with-coverage --cover-package=openmoo2 --cover-inclusive
after_success:
  - coveralls
